# Generated by Django 5.1 on 2024-09-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='pictures')),
                ('description', models.TextField()),
                ('department', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
