# Generated by Django 5.1 on 2024-09-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0002_trainee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postedcontentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_urls', models.URLField()),
                ('documents_urls', models.URLField()),
            ],
        ),
    ]
