# Generated by Django 5.1 on 2024-09-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0003_postedcontentes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Postedcontentes',
        ),
        migrations.AddField(
            model_name='contents',
            name='documents_urls',
            field=models.URLField(default='null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contents',
            name='estimated_time',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contents',
            name='video_urls',
            field=models.URLField(default='null'),
            preserve_default=False,
        ),
    ]
