# Generated by Django 5.1 on 2024-09-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0004_delete_postedcontentes_contents_documents_urls_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mandatory_trainings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='pictures')),
                ('description', models.TextField()),
                ('department', models.CharField(max_length=100)),
                ('video_urls', models.URLField()),
                ('documents_urls', models.URLField()),
                ('estimated_time', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
    ]
